#!/bin/sh
# elvis: anonymouse 	-- Browse through the Anonymouse.org as the proxy
# Author: Ali Gündüz <gndz.ali@gmail.com>
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Visit a URL with Anonymouse.org's web proxy
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://anonymouse.org/anonwww.html"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://anonymouse.org/cgi-bin/anon-www.cgi/${escaped_args}"
fi
