#!/bin/sh
# elvis: eksisozluk 	-- Search the Eksi Sozluk hypertext dictionary
# Author: Ali Gündüz <gndz.ali@gmail.com>
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Look up a term in Eksi Sozluk (sozluk.sourtimes.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://sozluk.sourtimes.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://sozluk.sourtimes.org/show.asp?t=${escaped_args}"
fi
