#!/bin/sh
# elvis: seslisozluk 	-- Search the Sesli Sozluk English-Turkish & Turkish-English dictionary
# Author: Ali Gündüz <gndz.ali@gmail.com>
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Look up a Turkish or English word in Sesli Sozluk (seslisozluk.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://seslisozluk.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.seslisozluk.com/?word=${escaped_args}"
fi
